# Generated by Django 2.2.4 on 2020-01-26 16:00

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsession',
            name='difficulty',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
