# Generated by Django 2.2.4 on 2020-01-27 16:47

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_game', '0003_remove_subsession_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='treatment',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
