# Generated by Django 2.2.12 on 2022-04-14 00:17

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manipulation_check_group', to='otree.Session')),
            ],
            options={
                'db_table': 'manipulation_check_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manipulation_check_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'manipulation_check_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('sense_control', otree.db.models.StringField(choices=[['None', 'Hakuna hata kidogo'], ['Little', 'Kidogo'], ['Moderate', 'Wastani'], ['A Lot', 'Kiwango kiKubwa'], ['Complete control', 'Kiwango kikubwa sana']], max_length=10000, null=True, verbose_name='Ulihisi una uwezo kiasi gani kudhibiti alama ulizopokea kwenye mchezo uliocheza sasa hivi?')),
                ('stai_calm', otree.db.models.StringField(choices=[['None', 'Hakuna hata kidogo'], ['Little', 'Kidogo'], ['Moderate', 'Wastani'], ['Very much', 'Kiwango kikubwa sana']], max_length=10000, null=True, verbose_name='Nahisi utulivu')),
                ('stai_tense', otree.db.models.StringField(choices=[['None', 'Hakuna hata kidogo'], ['Little', 'Kidogo'], ['Moderate', 'Wastani'], ['Very much', 'Kiwango kikubwa sana']], max_length=10000, null=True, verbose_name='Niko na hofu')),
                ('stai_upset', otree.db.models.StringField(choices=[['None', 'Hakuna hata kidogo'], ['Little', 'Kidogo'], ['Moderate', 'Wastani'], ['Very much', 'Kiwango kikubwa sana']], max_length=10000, null=True, verbose_name='Nihisi kukasiraka')),
                ('stai_relaxed', otree.db.models.StringField(choices=[['None', 'Hakuna hata kidogo'], ['Little', 'Kidogo'], ['Moderate', 'Wastani'], ['Very much', 'Kiwango kikubwa sana']], max_length=10000, null=True, verbose_name='Niko mtulivu')),
                ('stai_content', otree.db.models.StringField(choices=[['None', 'Hakuna hata kidogo'], ['Little', 'Kidogo'], ['Moderate', 'Wastani'], ['Very much', 'Kiwango kikubwa sana']], max_length=10000, null=True, verbose_name='Nahisi kuridhika')),
                ('stai_worried', otree.db.models.StringField(choices=[['None', 'Hakuna hata kidogo'], ['Little', 'Kidogo'], ['Moderate', 'Wastani'], ['Very much', 'Kiwango kikubwa sana']], max_length=10000, null=True, verbose_name='Nina wasiwasi')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manipulation_check.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manipulation_check_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manipulation_check_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manipulation_check.Subsession')),
            ],
            options={
                'db_table': 'manipulation_check_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manipulation_check.Subsession'),
        ),
    ]
