# Generated by Django 2.2.4 on 2020-01-24 13:19

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_survey_group', to='otree.Session')),
            ],
            options={
                'db_table': 'pre_survey_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_survey_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'pre_survey_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('exp_murder', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Murder, homicide, or lynching')),
                ('exp_assault', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Assault or attack')),
                ('exp_mugging', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Mugging')),
                ('exp_dvgbf', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Domestic violence, or gender based violence')),
                ('exp_riot', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Riot violence or police violence')),
                ('exp_arson', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Arson')),
                ('exp_witchcraft', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Witchcraft')),
                ('exp_other', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Other')),
                ('victim', otree.db.models.StringField(choices=[['self', 'Myself'], ['parent_child_spouse', 'My parent, child, or spouse'], ['other_family', 'Another family member'], ['neighbor_friend', 'A neighbor or close friend'], ['someone_else', 'Someone else I know']], max_length=10000, null=True, verbose_name='In the most recent incident, who was the victim?')),
                ('belief_indiv', otree.db.models.StringField(choices=[[0, 'Does not describe my belief'], [1, 'Slightly describes my belief'], [2, 'Moderately describes my belief'], [3, 'Mostly describes my belief'], [4, 'Completely describes my belief']], max_length=10000, null=True)),
                ('belief_ident', otree.db.models.StringField(choices=[[0, 'Does not describe my belief'], [1, 'Slightly describes my belief'], [2, 'Moderately describes my belief'], [3, 'Mostly describes my belief'], [4, 'Completely describes my belief']], max_length=10000, null=True)),
                ('belief_situ', otree.db.models.StringField(choices=[[0, 'Does not describe my belief'], [1, 'Slightly describes my belief'], [2, 'Moderately describes my belief'], [3, 'Mostly describes my belief'], [4, 'Completely describes my belief']], max_length=10000, null=True)),
                ('belief_behav', otree.db.models.StringField(choices=[[0, 'Does not describe my belief'], [1, 'Slightly describes my belief'], [2, 'Moderately describes my belief'], [3, 'Mostly describes my belief'], [4, 'Completely describes my belief']], max_length=10000, null=True)),
                ('belief_rand', otree.db.models.StringField(choices=[[0, 'Does not describe my belief'], [1, 'Slightly describes my belief'], [2, 'Moderately describes my belief'], [3, 'Mostly describes my belief'], [4, 'Completely describes my belief']], max_length=10000, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pre_survey.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_survey_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_survey_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pre_survey.Subsession')),
            ],
            options={
                'db_table': 'pre_survey_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pre_survey.Subsession'),
        ),
    ]
