# Generated by Django 2.2.4 on 2020-01-24 13:41

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='exp_arson',
            field=otree.db.models.BooleanField(blank=True, choices=[[False, 'False'], [True, 'True']], null=True, verbose_name='Arson'),
        ),
        migrations.AlterField(
            model_name='player',
            name='exp_assault',
            field=otree.db.models.BooleanField(blank=True, choices=[[False, 'False'], [True, 'True']], null=True, verbose_name='Assault or attack'),
        ),
        migrations.AlterField(
            model_name='player',
            name='exp_dvgbf',
            field=otree.db.models.BooleanField(blank=True, choices=[[False, 'False'], [True, 'True']], null=True, verbose_name='Domestic violence, or gender based violence'),
        ),
        migrations.AlterField(
            model_name='player',
            name='exp_mugging',
            field=otree.db.models.BooleanField(blank=True, choices=[[False, 'False'], [True, 'True']], null=True, verbose_name='Mugging'),
        ),
        migrations.AlterField(
            model_name='player',
            name='exp_murder',
            field=otree.db.models.BooleanField(blank=True, choices=[[False, 'False'], [True, 'True']], null=True, verbose_name='Murder, homicide, or lynching'),
        ),
        migrations.AlterField(
            model_name='player',
            name='exp_other',
            field=otree.db.models.BooleanField(blank=True, choices=[[False, 'False'], [True, 'True']], null=True, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='player',
            name='exp_riot',
            field=otree.db.models.BooleanField(blank=True, choices=[[False, 'False'], [True, 'True']], null=True, verbose_name='Riot violence or police violence'),
        ),
        migrations.AlterField(
            model_name='player',
            name='exp_witchcraft',
            field=otree.db.models.BooleanField(blank=True, choices=[[False, 'False'], [True, 'True']], null=True, verbose_name='Witchcraft'),
        ),
    ]
