# Generated by Django 2.2.4 on 2020-01-24 13:53

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_survey', '0002_auto_20200124_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='prior_exposure',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
