# Generated by Django 2.2.4 on 2020-01-26 08:32

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_survey', '0007_auto_20200126_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='belief_behav',
            field=otree.db.models.StringField(choices=[['Does not describe my belief', 'Does not describe my belief'], ['Slightly describes my belief', 'Slightly describes my belief'], ['Moderately describes my belief', 'Moderately describes my belief'], ['Mostly describes my belief', 'Mostly describes my belief'], ['Completely describes my belief', 'Completely describes my belief']], max_length=10000, null=True, verbose_name='I think the perpetrator chose a target based on something they were doing or something they had that made them a target'),
        ),
        migrations.AlterField(
            model_name='player',
            name='belief_ident',
            field=otree.db.models.StringField(choices=[['Does not describe my belief', 'Does not describe my belief'], ['Slightly describes my belief', 'Slightly describes my belief'], ['Moderately describes my belief', 'Moderately describes my belief'], ['Mostly describes my belief', 'Mostly describes my belief'], ['Completely describes my belief', 'Completely describes my belief']], max_length=10000, null=True, verbose_name='I think the perpetrator chose their target based on tribe, clan, gender, or some other part of identity'),
        ),
        migrations.AlterField(
            model_name='player',
            name='belief_indiv',
            field=otree.db.models.StringField(choices=[['Does not describe my belief', 'Does not describe my belief'], ['Slightly describes my belief', 'Slightly describes my belief'], ['Moderately describes my belief', 'Moderately describes my belief'], ['Mostly describes my belief', 'Mostly describes my belief'], ['Completely describes my belief', 'Completely describes my belief']], max_length=10000, null=True, verbose_name='I think the perpetrator was looking for a specific person'),
        ),
        migrations.AlterField(
            model_name='player',
            name='belief_rand',
            field=otree.db.models.StringField(choices=[['Does not describe my belief', 'Does not describe my belief'], ['Slightly describes my belief', 'Slightly describes my belief'], ['Moderately describes my belief', 'Moderately describes my belief'], ['Mostly describes my belief', 'Mostly describes my belief'], ['Completely describes my belief', 'Completely describes my belief']], max_length=10000, null=True, verbose_name='I think what happened was just random'),
        ),
        migrations.AlterField(
            model_name='player',
            name='belief_situ',
            field=otree.db.models.StringField(choices=[['Does not describe my belief', 'Does not describe my belief'], ['Slightly describes my belief', 'Slightly describes my belief'], ['Moderately describes my belief', 'Moderately describes my belief'], ['Mostly describes my belief', 'Mostly describes my belief'], ['Completely describes my belief', 'Completely describes my belief']], max_length=10000, null=True, verbose_name='I think it was just a matter of being in the wrong place at the wrong time'),
        ),
    ]
