# Generated by Django 2.2.4 on 2020-01-26 14:41

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_survey', '0021_auto_20200126_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='victim',
            field=otree.db.models.StringField(choices=[['self', 'Mimi Mwenyewe'], ['parent_child_spouse', 'Wazazi wangu, mtoto wangu ama mpenzi wangu'], ['other_family', 'Mtu mwingine kwenye familia'], ['neighbor_friend', 'Rafiki wa karibu ama jirani'], ['someone_else', 'Mtu mwingine ninaye mjua']], max_length=10000, null=True, verbose_name='Kwa kila tukio liliofanyika hivi karibuni, muathirika alikuwa ni nani?'),
        ),
    ]
