# Generated by Django 2.2.4 on 2020-01-27 18:05

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('outcome_2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='timeout',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
