# Generated by Django 2.2.4 on 2020-01-26 08:35

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='catches',
        ),
        migrations.RemoveField(
            model_name='player',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='player',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='player',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='player',
            name='score',
        ),
        migrations.AddField(
            model_name='player',
            name='misses',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
