# Generated by Django 2.2.4 on 2020-01-26 10:10

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_game', '0002_auto_20200126_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='clicks',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='cost',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='expense',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
