# Generated by Django 2.2.4 on 2020-01-26 11:12

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_game', '0004_auto_20200126_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='score',
            field=otree.db.models.IntegerField(blank=True, null=True),
        ),
    ]
