# Generated by Django 2.2.4 on 2020-01-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_game', '0005_auto_20200126_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='clicks',
        ),
    ]
