# Generated by Django 2.2.4 on 2020-01-26 11:15

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_game', '0006_remove_player_clicks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='hits',
        ),
        migrations.AddField(
            model_name='player',
            name='catches',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
